Algoritmo "ex2209"

Var
nome: caracter
idade: inteiro
genero: logico

Inicio
escreval ("boa noite")
escreval ("vou te fazer uma pergunta, presta atenção")
escreval("-----------------------------------------")
escreva("Qual é seu nome? ")
leia (nome)
escreval("-----------------------------------------")
escreva ("Qual sua idade? ")
leia (idade)
escreval("-----------------------------------------")
escreval("Seu gênero é feminino? v/f ")
leia (genero)
se (genero = "v" )
   escreval ("feminino")
senao
   escreval ("masculino")


Fimalgoritmo