Algoritmo "PA1509"

Var
nome: caracter
idade: inteiro
email: caracter


Inicio
//nome <- "Daniel"
//idade <- 25
//email <- "danielsallesse@gmail.com"

escreva ("Digite seu nome: ")
leia (nome)

escreva ("Digite sua idade: ")
leia (idade)

escreva ("Digite seu email: ")
leia (email)

//escreval(nome)
//escreval(idade)
//escreval(email)

escreval ("Meu nome é ", nome, ", minha idade é", idade, " anos", " e meu email é ", email)


Fimalgoritmo