Algoritmo "programaexemplo"

Var
marca:caracter

n1: inteiro
n2: inteiro
soma: inteiro

ano: inteiro



Inicio
escreval ("Estamos iniciando nosso algoritmo!")
escreval ("Hora do Lanchinho!")

marca <- "fiat"
escreval (marca)

ano <- 2023
escreval (ano)


escreval ("a marca do carro é " , marca, " e o ano é de", ano)



n1 <- 7
n2 <- 2
soma <- n1 + n2
escreva (n1 , " +", n2 , " =", soma)



 

Fimalgoritmo