Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/11/2023
Var
   // Seção de Declarações das variáveis
   nome: vetor [0 .. 3] de caractere
   i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   nome[0] <- "a"
   nome[1] <- "b"
   nome[2] <- "c"
   nome[3] <- "d"
   escreval (nome[3])

   para i de 0 ate 2 passo 1 faca

      escreval(nome[i])
   fimpara
Fimalgoritmo